### ISSUE TITLE
Kostal 5.5

### ISSUE THREAD

**Issue by pergolafabio** [sla89/hassio-kostal-piko#11]
Hi, 

Does this integration also work with older webui? like kostal 5.5 , fw = 04.06 UI, 03.78 ?

![image](https://github.com/sla89/hassio-kostal-piko/assets/43251136/b65954b5-f725-4555-badf-b8878f243a60)

**Comment by sla89** [comment]
Hi,

I dont think so because this kind of inverter of Kostal does not expose any API as far as I know.

Have you tried it?

This is an [alternative](https://github.com/rcasula/kostalpiko-homeassistant) that should work.

**Comment by pergolafabio** [comment]
yeah, using the alternative now, its indeed older device
