### ISSUE TITLE
Unable to set update interval. 

### ISSUE THREAD

**Issue by teampyt** [sla89/hassio-kostal-piko#12]
Hi there, 
I need the power information quicker than currently given by this great work.
Is there  a way to set an interval for the update? 
I would need about 5 seconds interval.
Any ideas?

**Comment by sla89** [comment]
Hey,

currently it is set to 10s for all sensors. You have to modify the code at [this line](https://github.com/sla89/hassio-kostal-piko/blob/4edc59b39ac56285af4f00f9d21cf6bf9034e327/custom_components/kostal_piko/sensor.py#L28) and set the value to your wished interval.

I hope this helps.

**Comment by sla89** [comment]
@teampyt any update on this?

**Comment by sla89** [comment]
Closed because no more feedback provided. Cant help then.
Feel free to open it again when needed.
