### ISSUE TITLE
A lot of power on / off

### ISSUE THREAD

**Issue by pergolafabio** [sla89/hassio-kostal-piko#13]
Guys, came to ask here
My Kostal 5.5 DCS was replaced with a new NG model (green bar logo) very recently
What i now notice with the bad weather and quite dark outside in morning/evening, i see a lot of startup / downs of the NG
Seems it wants to start , but gets not enough power, to finally start... do you guys also see this?

![image](https://github.com/sla89/hassio-kostal-piko/assets/43251136/3eb94a73-c480-4300-92ac-37da76453224)

**Comment by pergolafabio** [comment]
Hi @wolframkorth  or @patricknitsch 

Sorry to tag you, but it seems you have the same device as me :-)

**Comment by sla89** [comment]
Sorry, I cant help because I have a PIKO IQ

**Comment by sla89** [comment]
@pergolafabio any update on this, othersise I close the issue. :)

**Comment by pergolafabio** [comment]
Still happening :-)

But seems moon had such a device :-(
