### ISSUE TITLE
Failure Updating Sensors since Core Update

### ISSUE THREAD

**Issue by patricknitsch** [sla89/hassio-kostal-piko#7]
Hello,

since the Core Update I have a lot of problems with the Kostal Entities. I get a lot of errors while updating the sensors. See the log:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.kostal_piko.sensor
Source: custom_components/kostal_piko/sensor.py:89 
Integration: kostal_piko (documentation, issues) 
First occurred: 17:37:24 (156 occurrences) 
Last logged: 17:43:34

Failed updating sensor Kostal PIKO Phase 1 Power: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.0.92', port=80): Max retries exceeded with url: /api/dxs.json?dxsEntries=67109379 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6e1ceb5960>, 'Connection to 192.168.0.92 timed out. (connect timeout=10)'))"))
Failed updating sensor Kostal PIKO DC Input 3 Power: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.0.92', port=80): Max retries exceeded with url: /api/dxs.json?dxsEntries=33555715 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6e1d354700>, 'Connection to 192.168.0.92 timed out. (connect timeout=10)'))"))
Failed updating sensor Kostal PIKO Phase 2 Current: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.0.92', port=80): Max retries exceeded with url: /api/dxs.json?dxsEntries=67109633 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6e1ceb6230>, 'Connection to 192.168.0.92 timed out. (connect timeout=10)'))"))
Failed updating sensor Kostal PIKO Phase 1 Voltage: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.0.92', port=80): Max retries exceeded with url: /api/dxs.json?dxsEntries=67109378 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6e1ceb5090>, 'Connection to 192.168.0.92 timed out. (connect timeout=10)'))"))
Failed updating sensor Kostal PIKO Phase 3 Current: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.0.92', port=80): Max retries exceeded with url: /api/dxs.json?dxsEntries=67109889 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6e1ceb7940>, 'Connection to 192.168.0.92 timed out. (connect timeout=10)'))"))

Firmware and Software are the same as before the core update.

Does anyone have an idea how I can solve the problem?

Thanks a lot.

Many regards

**Comment by dinomyte76** [comment]
Hi @patricknitsch 
it seems that this is probably the same issue as here:
https://github.com/sla89/hassio-kostal-piko/issues/6

I do also have a lot of issues since the last core update...

**Comment by sla89** [comment]
@patricknitsch Do you still have the problem or has it been solved after another core update?

BTW there is a new release available that fixes #6, maybe it solves your problem too.

**Comment by patricknitsch** [comment]
I will check this. Thanks!

**Comment by sla89** [comment]
@patricknitsch any update on this?

**Comment by patricknitsch** [comment]
Looks good. No more errors occurred.
